volumes:
  db:
    driver: local
  cache:
    driver: local

networks:
  ${DOCKER_NETWORK}:

services:
  php:
    build: ./${PHP_VERSION}
    container_name: php
    volumes_from:
      - source
    links:
      - db
      - memcached
    environment:
      - TZ=${TIME_ZONE}
    stdin_open: true
    tty: true
    networks:
      - ${DOCKER_NETWORK}
    restart: unless-stopped
  web_server:
    build: ./${WEB_SERVER_TYPE}
    container_name: web_server
    depends_on:
      - source
    volumes_from:
      - source
    ports:
      - '${INTERFACE}:80:80'
      - '${INTERFACE}:443:443'
    links:
      - php
    networks:
      - ${DOCKER_NETWORK}
    environment:
      - TZ=${TIME_ZONE}
    stdin_open: true
    tty: true
    restart: unless-stopped
  db:
    build: ./${DB_SERVER_TYPE}
    container_name: db
    volumes:
      - ./${DB_SERVER_TYPE}/init:/docker-entrypoint-initdb.d
    volumes_from:
      - source
    ports:
      - '${INTERFACE}:3306:3306'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TIME_ZONE}
    command: mysqld --user=root --sql-mode=""
    networks:
      - ${DOCKER_NETWORK}
    stdin_open: true
    tty: true
    restart: unless-stopped
  memcached:
    image: memcached:latest
    container_name: memcached
    volumes_from:
      - source
    ports:
      - '${INTERFACE}:11211:11211'
    networks:
      - ${DOCKER_NETWORK}
    environment:
      - TZ=${TIME_ZONE}
    stdin_open: true
    tty: true
    restart: unless-stopped
#  adminer:
#    image: dockette/adminer:full
#    container_name: adminer
#    links:
#      - db:db
#    ports:
#      - '${INTERFACE}:8080:80'
#    environment:
#      UPLOAD: 1024M # upload_max_filesize, post_max_size
#      TZ: ${TIME_ZONE}
#    restart: unless-stopped
#    stdin_open: true
#    tty: true
#    networks:
#      - docker_for_bitrix
  phpmyadmin:
    container_name: phpMyAdmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    networks:
      - ${DOCKER_NETWORK}

  source:
    image: alpine:latest
    container_name: source
    volumes:
      - ./logs/${WEB_SERVER_TYPE}:/var/log/${WEB_SERVER_TYPE}
      - ./logs/php:/var/log/php
      - ./logs/db:/var/log/mysql
      - ./logs/memcached:/var/log/memcached
      - db:/var/lib/mysql
      - cache:/var/lib/memcached
      - ${SITE_PATH}:/var/www/bitrix
      - ${CERTS_PATH}:/etc/nginx/certs
    networks:
      - ${DOCKER_NETWORK}
